POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
    "title": "The power of writing blogs",
    "url": "https://hustlebloggercom.wordpress.com/2021/09/22/suc-manh-cua-loi-hua/#more-1424",
    "likes": 35,
    "author": "Hoang Long",
    "userId": "61c852d3a7f131403ab85062"
}

###
GET  http://localhost:3003/api/blogs/

###
POST http://localhost:3003/api/users/
Content-Type: application/json

{
    "username": "luongkill1234567890",
    "name": "Nguyen Pham",
    "password": "luong12345",
    "blogs": []
}

###
GET  http://localhost:3003/api/users/